name: Cross-platform Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv sync

      - name: Build executable
        run: |
          uv run pmake.py build
        env:
          KIVY_NO_ARGS: 1

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: pystun3-gui-${{ matrix.os }}
          path: dist/*
