name: Cross-platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install build tools
      run: |
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --name pystun-gui --window main.py
      env:
        KIVY_NO_ARGS: 1
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: stun-checker-${{ matrix.os }}
        path: dist/*