name: Cross-platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install build tools
      run: |
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --name stun-checker main.py
      env:
        KIVY_NO_ARGS: 1
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: stun-checker-${{ matrix.os }}
        path: dist/*

  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev
        
        python -m pip install --upgrade pip
        pip install cython==0.29.36 buildozer
        
    - name: Configure Buildozer
      run: |
        buildozer init
        echo "[app]" > buildozer.spec
        echo "title = STUN Checker" >> buildozer.spec
        echo "package.name = stunchecker" >> buildozer.spec
        echo "package.domain = org.test" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,atlas,json" >> buildozer.spec
        echo "version = 0.1" >> buildozer.spec
        echo "requirements = python3,kivy,pystun3" >> buildozer.spec
        echo "orientation = portrait" >> buildozer.spec
        echo "fullscreen = 0" >> buildozer.spec
    
    - name: Build Android APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: stun-checker-android
        path: bin/*.apk